name: UdaConnect - Package with Docker
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - Backend service
        uses: docker/build-push-action@v2
        with:
          context: ./Project_Starter_Files-Building_a_Metrics_Dashboard/app/backend
          file: ./Project_Starter_Files-Building_a_Metrics_Dashboard/app/backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: aplacidi/udac-obs-backend-service:latest